name: Update dependencies

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# on:
#   schedule:
#     - cron: '0 8 * * 1' # At 08:00 on Monday. https://crontab.guru/#0_8_*_*_1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Update dependencies
        run: npx npm-check-updates -u
      - name: Install dependencies
        run: npm install
      - name: Raise pull request
        uses: actions/github-script@0.4.0
        with:
          debug: true
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { readFileSync } = require('fs');
            const { resolve } = require('path');
            const { execSync } = require('child_process');

            const changedFiles = execSync('git diff --name-only')
              .toString()
              .split('\n')
              .filter(Boolean);
            console.log({ changedFiles });

            if (!changedFiles.includes('package.json')) {
              return;
            }

            const activeBranchRegex = /^\* (.*)$/;
            const baseBranch = execSync('git branch')
              .toString()
              .split('\n')
              .map(branch => {
                const match = activeBranchRegex.exec(branch);
                return match && match[1];
              })
              .find(Boolean);
            console.log({ baseBranch });
            const parentSha = execSync('git rev-parse HEAD')
              .toString()
              .trim();
            console.log({ parentSha });
            const branch = `update-dependencies-${
              new Date()
                .toISOString()
                .replace(/[T:]/g, '-')
                .split('.')[0]
            }`;
            console.log({ branch });
