name: Update dependencies

on:
  schedule:
    - cron: '0 7 * * 1' # At 07:00 GTM on Monday. https://crontab.guru/#0_8_*_*_1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Update dependencies
        run: npx npm-check-updates -u
      - name: Install dependencies
        run: npm install
      - name: Raise pull request
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { readFileSync } = require('fs');
            const { resolve } = require('path');

            const baseBranch = 'master';
            const branch = `update-dependencies-${new Date().toISOString().replace(/[T:]/g,'-').split('.')[0]}`;

            const baseBranchRef = await github.git.getRef({
              ...context.repo,
              ref: `heads/${baseBranch}`
            });
            const parentSha = baseBranchRef.data.object.sha;

            const tree = await github.git.createTree({
              ...context.repo,
              base_tree: parentSha,
              tree: ['package.json', 'package-lock.json'].map(path => ({
                path,
                mode: '100644',
                content: readFileSync(resolve(process.cwd(), path), 'utf8')
              }))
            });

            const commit = await github.git.createCommit({
              ...context.repo,
              message: 'Update dependencies',
              tree: tree.data.sha,
              parents: [parentSha]
            });

            await github.git.createRef({
              ...context.repo,
              ref: `refs/heads/${branch}`,
              sha: commit.data.sha
            });

            await github.pulls.create({
              ...context.repo,
              title: branch.replace(/-/g,' '),
              head: branch,
              base: baseBranch
            });
