name: Update dependencies

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

on:
  schedule:
    - cron: '0 7 * * 1' # At 07:00 GMT on Monday. https://crontab.guru/#0_7_*_*_1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Update dependencies
        run: npx npm-check-updates -u
      - name: Install dependencies
        run: npm install
      - name: Raise pull request
        uses: actions/github-script@0.4.0
        with:
          github-token: ${{secrets.UPDATE_DEPENDENCIES_TOKEN}}
          script: |
            const { readFileSync } = require('fs');
            const { resolve } = require('path');
            const { execSync } = require('child_process');

            const changedFiles = execSync('git diff --name-only')
              .toString()
              .split('\n')
              .filter(Boolean);

            if (!changedFiles.includes('package.json')) {
              return;
            }

            const baseBranch = execSync('git branch')
              .toString()
              .split('\n')
              .map(branch => {
                const match = /^\* (.*)$/.exec(branch);
                return match && match[1];
              })
              .find(Boolean);

            const parentSha = execSync('git rev-parse HEAD')
              .toString()
              .trim();

            const branch = `update-dependencies-${
              new Date()
                .toISOString()
                .replace(/[T:]/g, '-')
                .split('.')[0]
            }`;

            const tree = await github.git.createTree({
              ...context.repo,
              base_tree: parentSha,
              tree: changedFiles.map(path => ({
                path,
                mode: '100644',
                content: readFileSync(resolve(process.cwd(), path), 'utf8')
              }))
            });

            const commit = await github.git.createCommit({
              ...context.repo,
              message: 'Update dependencies',
              tree: tree.data.sha,
              parents: [parentSha]
            });

            await github.git.createRef({
              ...context.repo,
              ref: `refs/heads/${branch}`,
              sha: commit.data.sha
            });

            await github.pulls.create({
              ...context.repo,
              title: branch.replace(/-/g,' '),
              head: branch,
              base: baseBranch
            });
